### ISSUE TITLE
Weird article happenings

### ISSUE THREAD

**Issue by goodroot** [paweljw/bookstore-frontend#1]
Hey Pawel!

Your tutorials are really, _really_ good. Thank you! I've enjoyed reading them. They are some of the best I have read.

I just wanted to let you know that the link in your intro goes to: http://localhost:1313/2017/07/rails-5.1-api-app-part-4-authentication-and-authorization/. 💃 

Cheers, buddy! Great work. I'm going to start a project based around your work. Thanks again.

**Comment by paweljw** [comment]
I should probably put in a git hook that prevents committing links to localhost, this is... hardly the first time it happened ;) Thank you for pointing it out, it should be all sorted out now.

I'm thrilled that you're finding the posts useful, please share your project if and when you feel comfortable doing so!
